#!/bin/env python
import sys
from PyQt4 import QtGui
from calibration.calibration import GUI

if __name__ == "__main__":
    app = QtGui.QApplication(sys.argv)
    calib = GUI()
    calib.app = app
    calib.show()
    sys.exit(app.exec_())
